name: DB Sync

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  db-sync:
    runs-on: self-hosted

    steps:
      - name: Create db_sync folder
        uses: appleboy/ssh-action@v0.1.10
        with:
            host:     ${{ secrets.HOST      }}
            username: ${{ secrets.USERNAME  }}
            password: ${{ secrets.PASSWD    }}
            script: |
              screen -ls | grep db_sync | cut -d. -f1 | awk '{print $1}' | xargs -r kill
              screen -dmS db_sync
              screen -S db_sync -X stuff 'cd runner/_work/spamtong/spamtong\n'
              screen -S db_sync -X stuff 'chmod +x db_sync.sh\n'
              screen -S db_sync -X stuff './db_sync.sh\n'
      - name: Push to Repository
        uses: tech-thinker/push-to-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          user-name: "charpplie[bot]"
          source-directory: "db"
          destination-github-username: "charpplie"
          destination-repository-name: "SpamtongDatabase"
          target-branch: master