name: DB Sync

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  db-sync:
    runs-on: self-hosted

    steps:
    - name: Clone previous db files
        uses: actions/checkout@master
        with:
          repository: charpplie/SpamtongDatabase
          token: ${{ secrets.TOKEN }}
          fetch-depth: 2

    - name: Create db_sync folde
        run: |
          chmod +x ./db_sync.sh
          ./db_sync.sh
        shell: bash

      - name: Push to Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: 'dbsync'
          destination-github-username: 'charpplie'
          destination-repository-name: 'SpamtongDatabase'
          user-email: maksohuman@gmail.com
          target-branch: master