name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:
    branches: master
    

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and run
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Deploy
        run: cd /home/charlie/actions-runner/_work/spamtong/spamtong && nohup npm install > /dev/null 2>&1 & && nohup npm run dev > /dev/null 2>&1 &
