name: CI/CD Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: manjaro-latest
    steps:
      - name: Build and run
        run: |
          npm install
          npm run dev
