name: Main

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prodbuild:
    runs-on: self-hosted

    steps:
      - name: Push to Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: 'db'
          destination-github-username: 'charpplie'
          destination-repository-name: 'SpamtongDatabase'
          user-email: maksohuman@gmail.com
          target-branch: master

      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Run Spamtong on self-hosted runner via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
            host:     ${{ secrets.HOST      }}
            username: ${{ secrets.USERNAME  }}
            password: ${{ secrets.PASSWD    }}
            script: |
              screen -ls | grep spamtong | cut -d. -f1 | awk '{print $1}' | xargs -r kill
              screen -dmS spamtong
              screen -S spamtong -X stuff 'cd runner/_work/spamtong/spamtong\n'
              screen -S spamtong -X stuff 'npm install\n'
              screen -S spamtong -X stuff 'npm run dev\n'