name: Main

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["script-workflow"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prodbuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: npm install

      - name: Start Spamtong
        run: |
          npm run dev

      - run: sleep 1m

      - name: Trigger new workflow run
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'