name: Main

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prodbuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: npm install

      - name: Start Spamtong
        run: |
          npm run dev
          node -e "setTimeout(() => { console.log('End Node.js Script'); process.exit(); }, 18000000)"
