name: Rofls

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rofls:
    runs-on: self-hosted
    steps:
      - name: Start Rofls session on self-hosted runner via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host:     ${{ secrets.HOST      }}
          username: ${{ secrets.USERNAME  }}
          password: ${{ secrets.PASSWD    }}
          script: |
            screen -ls | grep rofls_zov | cut -d. -f1 | awk '{print $1}' | xargs -r kill
            screen -dmS rofls_zov
            screen -S rofls_zov -X stuff 'cd actions-runner/_work/spamtong/spamtong\n'
            screen -S rofls_zov -X stuff 'npm run rofls\n'