name: Main

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prodbuild:
    runs-on: self-hosted

    steps:
      - name: Restart Spamtong session on self-hosted runner via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
            host:     ${{ secrets.HOST      }}
            username: ${{ secrets.USERNAME  }}
            password: ${{ secrets.PASSWD    }}
            script: |
              screen -ls | grep spamtong | cut -d. -f1 | awk '{print $1}' | xargs -r kill
              screen -dmS spamtong
              screen -S spamtong -X stuff 'cd actions-runner/_work/spamtong/spamtong\n'
              screen -S spamtong -X stuff 'npm run dev ${{ secrets.TOKEN }} ${{ secrets.APPID }}\n'