name: Push to Tracking Repo

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: self-hosted

    steps:
      - name: Creates output
        run: |
          chmod +x version.sh
          ./version.sh

      # - name: Push to Tracking repo
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API }}
      #   with:
      #     source-directory